action_name: admittance
kinematic_chain_base_link: yumi_base_link
loop_rate: 150
left_arm:
  kdl_eef_frame: yumi_link_7_l
  gripping_frame: yumi_link_7_l
  has_ft_sensor: true
  sensor_frame: optodaq_l_sensor_link
  sensor_topic: /yumi/optodaq_l_compensated

right_arm:
  kdl_eef_frame: yumi_link_7_r
  gripping_frame: yumi_link_7_r
  has_ft_sensor: true
  sensor_frame: optodaq_r_sensor_link
  sensor_topic: /yumi/optodaq_r_compensated

kdl_manager:
  eps: 0.001
  max_tf_attempts: 10
  ikvel_solver: nso
  nso_weight: 4

admittance:
  settling_time: 1.0
  damping_ratio: 2.0
  K_p:
    data: [300, 0, 0, 0, 0, 0,
           0, 300, 0, 0, 0, 0,
           0, 0, 300, 0, 0, 0,
           0, 0, 0, 8.0, 0, 0,
           0, 0, 0, 0, 8.0, 0,
           0, 0, 0, 0, 0, 8.0]

  force_dead_zone: 0.75
  torque_dead_zone: 0.1
  position_offset: 0.1
  max_linear_acceleration: 1.1
  max_linear_velocity: 0.05
  max_angular_acceleration: 1.5
  max_angular_velocity: 0.1
  linear_threshold: 0.00
  angular_threshold: 0.00
