action_name: admittance
kinematic_chain_base_link: yumi_base_link
loop_rate: 250
left_arm:
  kdl_eef_frame: yumi_link_7_l
  gripping_frame: yumi_link_7_l
  has_ft_sensor: true
  sensor_frame: optodaq_l_sensor_link
  sensor_topic: /yumi/optodaq_l_compensated
  sensor_calib:
    data: [1.0, 0, 0, 0, 0, 0,
           0, 1.0, 0, 0, 0, 0,
           0, 0, 1.0, 0, 0, 0,
           0, 0, 0, 1.0, 0, 0,
           0, 0, 0, 0, 1.0, 0,
           0, 0, 0, 0, 0, 1.0]

right_arm:
  kdl_eef_frame: yumi_link_7_r
  gripping_frame: yumi_link_7_r
  has_ft_sensor: true
  sensor_frame: optodaq_r_sensor_link
  sensor_topic: /yumi/optodaq_r_compensated
  sensor_calib:
    data: [1.0, 0, 0, 0, 0, 0,
           0, 1.0, 0, 0, 0, 0,
           0, 0, 1.0, 0, 0, 0,
           0, 0, 0, 1.0, 0, 0,
           0, 0, 0, 0, 1.0, 0,
           0, 0, 0, 0, 0, 1.0]

kdl_manager:
  eps: 0.01
  max_tf_attempts: 10
  ikvel_solver: nso
  nso_weight: 40

admittance:
  settling_time: 2.5
  damping_ratio: 1.3
  K_p:
    data: [100, 0, 0, 0, 0, 0,
           0, 100, 0, 0, 0, 0,
           0, 0, 100, 0, 0, 0,
           0, 0, 0, 4.0, 0, 0,
           0, 0, 0, 0, 4.0, 0,
           0, 0, 0, 0, 0, 4.0]

  force_dead_zone: 0.75
  torque_dead_zone: 0.1
  position_offset: 0.1
  max_linear_acceleration: 1.1
  max_linear_velocity: 0.05
  max_angular_acceleration: 1.5
  max_angular_velocity: 0.1
  linear_threshold: 0.00
  angular_threshold: 0.00
