action_name: approach
kinematic_chain_base_link: yumi_base_link
loop_rate: 250
approach_arm:
  kdl_eef_frame: yumi_link_7_l
  gripping_frame: l_gripping_point
  has_ft_sensor: true
  sensor_frame: optodaq_l_sensor_link
  sensor_topic: /yumi/optodaq_l/ft_compensated
  sensor_calib:
    data: [1.0, 0, 0, 0, 0, 0,
           0, 1.0, 0, 0, 0, 0,
           0, 0, 1.0, 0, 0, 0,
           0, 0, 0, 1.0, 0, 0,
           0, 0, 0, 0, 1.0, 0,
           0, 0, 0, 0, 0, 1.0]

kdl_manager:
  eps: 0.01
  max_tf_attempts: 10
  ikvel_solver: nso
  nso_weight: 40

# Bellow here is for demo purposes of the ROS controller version only
ApproachRosController:
  type: yumi_experiments/ApproachRosController

  action_name: approach
  kinematic_chain_base_link: yumi_base_link
  loop_rate: 250
  approach_arm:
    kdl_eef_frame: yumi_link_7_l
    gripping_frame: l_gripping_point
    has_ft_sensor: true
    sensor_frame: optodaq_l_sensor_link
    sensor_topic: /yumi/optodaq_l/ft_compensated
    sensor_calib:
      data: [1.0, 0, 0, 0, 0, 0,
             0, 1.0, 0, 0, 0, 0,
             0, 0, 1.0, 0, 0, 0,
             0, 0, 0, 1.0, 0, 0,
             0, 0, 0, 0, 1.0, 0,
             0, 0, 0, 0, 0, 1.0]

  kdl_manager:
    eps: 0.01
    max_tf_attempts: 10
    ikvel_solver: nso
    nso_weight: 40
