move:
  action_name: /admittance_controller/admittance
approach:
  action_name: /approach_controller/approach
  approach_frame: l_gripping_point
ft_reset_services: [/yumi_left_arm_gravity_comp/calibrate_bias, /yumi_right_arm_gravity_comp/calibrate_bias]
right_arm:
  pose: [0.341, -0.339, 0.120, -0.649, 0.326, -0.195, 0.659]
left_arm:
  pose: [0.480, 0.086, 0.099, 0.699, 0.234, 0.128, 0.664]
