move:
  action_name: /admittance_controller/admittance
  timeout: 10
  calibrate_bias: false
folding:
  action_name: /folding_controller/fold
approach:
  action_name: /approach_controller/approach
  approach_frame: l_gripping_point
ft_reset_services: [/right_arm_gravity_compensation/calibrate_bias, /left_arm_gravity_compensation/calibrate_bias]
right_arm:
  pose: [0.609, -0.166, 0.574, 0.130, 0.688, 0.706, 0.109]
  joint_state: [1.01461, -2.36249, -0.97254, 0.35262, 2.49838, -0.97181, -3.51083] # third joint swapped with 7th
left_arm:
  pose: [0.409, 0.337, 0.571, 0.576, 0.398, 0.351, 0.622]
  joint_state: [-1.35061, -2.12945, 1.27969, 0.61195, 4.33682, -0.59895, -3.20706] # third joint swapped with 7th
