move:
  action_name: /admittance_controller/admittance
folding:
  action_name: /folding_controller/fold
approach:
  action_name: /approach_controller/approach
  approach_frame: l_gripping_point
ft_reset_services: [/yumi_left_arm_gravity_comp/calibrate_bias, /yumi_right_arm_gravity_comp/calibrate_bias]
right_arm:
  pose: [0.311, -0.339, 0.120, -0.649, 0.326, -0.195, 0.659]
  joint_state: [1.01461, -2.36249, -0.97254, 0.35262, 2.49838, -0.97181, -3.51083] # third joint swapped with 7th
left_arm:
  pose: [0.364, 0.179, 0.151, 0.699, 0.234, 0.128, 0.664]
  joint_state: [-1.35061, -2.12945, 1.27969, 0.61195, 4.33682, -0.59895, -3.20706] # third joint swapped with 7th
