move:
  action_name: /yumi/move
folding:
  action_name: /folding_controller/fold
approach:
  action_name: /approach_controller/approach
  approach_frame: l_gripping_point
ft_reset_services: [/yumi_left_arm_gravity_comp/calibrate_bias, /yumi_right_arm_gravity_comp/calibrate_bias]
right_arm:
  joint_state: [1.37998, -1.41813, -1.23957, -0.10570, -0.39259, 1.27131, 1.00927]
left_arm:
  joint_state: [-1.88020, -1.58646, 0.61070, 0.79583, 1.84154, 1.87208,  -2.59034]
